### ISSUE TITLE
The terminal and windows examples doesn't work when packaged

### ISSUE THREAD

**Issue by JarLob** [GoogleChromeLabs/carlo#118]
Tried to run all examples on Windows 10 1803 x64, packaged and unpackaged.
SystemInfo work fine, but terminal and windows examples don't.

The terminal example is stuck with black window. 
The windows example gives:

`(node:16552) UnhandledPromiseRejectionWarning: Error: net::ERR_NAME_NOT_RESOLVED at https://domain/main.html
    at navigate (C:\snapshot\windows\node_modules\puppeteer-core\lib\FrameManager.js:107:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\windows\node_modules\puppeteer-core\lib\helper.js:144:27)
    at Page.goto (C:\snapshot\windows\node_modules\puppeteer-core\lib\Page.js:624:49)
    at Page.<anonymous> (C:\snapshot\windows\node_modules\puppeteer-core\lib\helper.js:145:23)
    at Window.load (C:\snapshot\windows\node_modules\carlo\lib\carlo.js:349:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:16552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Chrome version 71.0.3578.98 (Official Build) (64-bit)

**Comment by futurepaycc** [comment]
same problem:
Version 75.0.3770.100 (Official Build) Arch Linux (64-bit)
