### ISSUE TITLE
The given example failed to run. (Protocol error - Browser.grantPermissions.)

### ISSUE THREAD

**Issue by Sar-Kerson** [GoogleChromeLabs/carlo#12]
Hello!
I try to run the given example `systeminfo` but failed. Here's the error throwed:
```
Error: Protocol error (Browser.grantPermissions): 'Browser.grantPermissions' wasn't found
    at Promise (/media/sar/extlinux/codes/SarKerson/to_learn/carlo/examples/systeminfo/node_modules/puppeteer-core/lib/Connection.js:73:56)
    at new Promise (<anonymous>)
    at Connection.send (/media/sar/extlinux/codes/SarKerson/to_learn/carlo/examples/systeminfo/node_modules/puppeteer-core/lib/Connection.js:72:12)
    at BrowserContext.overridePermissions (/media/sar/extlinux/codes/SarKerson/to_learn/carlo/examples/systeminfo/node_modules/puppeteer-core/lib/Browser.js:314:28)
    at BrowserContext.<anonymous> (/media/sar/extlinux/codes/SarKerson/to_learn/carlo/examples/systeminfo/node_modules/puppeteer-core/lib/helper.js:145:23)
    at Object.launch (/media/sar/extlinux/codes/SarKerson/to_learn/carlo/examples/systeminfo/node_modules/carlo/lib/carlo.js:202:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
I can not figure out what's wrong here.
**My environment infos:**
- Ubuntu 18.04.1 LTS
- Chome: Version 69.0.3497.100 (Official Build) (64-bit)
- node: v8.10.0

**Comment by pavelfeldman** [comment]
Your Chrome is [out of date](http://omahaproxy.appspot.com/), probably suggesting the restart to update. The current stable on Linux is 70.0.3538.77.

Carlo is new, so it relies upon some new Chrome APIs.
