### ISSUE TITLE
Added [app.serveOrigin] UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Dacturne** [GoogleChromeLabs/carlo#56]
_Originally posted by @pavelfeldman in https://github.com/GoogleChromeLabs/carlo/issues/45#issuecomment-436094420_
_Commit: https://github.com/GoogleChromeLabs/carlo/commit/e384301633c59061bac6aa6959e4566b4e45c598_

[App.serveOrigin(origin)](https://github.com/GoogleChromeLabs/carlo/blob/master/API.md#appserveoriginorigin) doesn't seem to work properly.

```
(node:2452) UnhandledPromiseRejectionWarning: TypeError: app.serveOrigin is not a function
    at carlo.launch.then (D:\Dokumenty\carlo-serve-origin-test\index.js:5:7)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:2452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vsemozhetbyt** [comment]
Did you update `carlo` to the last master state?

**Comment by Dacturne** [comment]
Yes, it's the latest.

**Comment by vsemozhetbyt** [comment]
H'm. I have a different issue:
```js
'use strict';

const carlo = require('carlo');

(async () => {
  const app = await carlo.launch();
  app.on('exit', () => process.exit());

  app.serveOrigin('https://example.org');
  await app.load('index.html');

  console.log(await app.evaluate(() => location.href));
})();
```

```
(node:2632) UnhandledPromiseRejectionWarning: Error: Please call app.serveFolder(__dirname) or point to other folder(s) with your web files
    at App.load (carlo\lib\carlo.js:122:13)
    at test.js:10:13
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:2632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catchblock, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Dacturne** [comment]
My bad,
`UnhandledPromiseRejectionWarning` with npm `0.9.11`
`master` results are same as yours

**Comment by vsemozhetbyt** [comment]
I can also get with this:
```
'use strict';

const carlo = require('carlo');

(async function main() {
  try {
    const app = await carlo.launch();
    app.on('exit', () => process.exit());

    app.serveOrigin('https://example.org');
    app.serveFolder('/');
    await app.load('index.html');

    console.log(await app.evaluate(() => location.href));
  } catch (err) {
    console.error(err);
  }
})();
```
(The location is a bit confusing though: `https://domain/index.html`)

Maybe doc example needs to be updated with `app.serveFolder()` added?

**Comment by Dacturne** [comment]
Perhaps it could be changed in `load()` ?
```javascript
  load(uri) {
    if (!this.www_.size) {
      if (this.wwwOrigin_) {
        this.www_.set('/');
      } else {
        this.page_.close();
        throw new Error('Please call app.serveFolder(__dirname) or point to ' +
                        'other folder(s) with your web files');
      }
    }
    return this.page_.goto(`https://domain/${uri}`, {timeout: 0});
  }
```
