### ISSUE TITLE
[Problem] Domain name

### ISSUE THREAD

**Issue by tsengkasing** [GoogleChromeLabs/carlo#9]
It can't resolve the domain name "domain" with the URL "https://domain/${uri}".
Could you please tell me how I can fix it ?

```bash
$ node sample.js
(node:16568) UnhandledPromiseRejectionWarning: Error: net::ERR_NAME_NOT_RESOLVED at https://domain/example.html
    at navigate (D:\Projects\Demo\carlo\node_modules\puppeteer-core\lib\FrameManager.js:103:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (D:\Projects\Demo\carlo\node_modules\puppeteer-core\lib\helper.js:144:27)
    at Page.goto (D:\Projects\Demo\carlo\node_modules\puppeteer-core\lib\Page.js:579:49)
    at Page.<anonymous> (D:\Projects\Demo\carlo\node_modules\puppeteer-core\lib\helper.js:145:23)
    at App.load (D:\Projects\Demo\carlo\node_modules\carlo\lib\carlo.js:95:23)
    at D:\Projects\Demo\carlo\sample.js:7:12
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by pavelfeldman** [comment]
Check out the example in the README.md. You would get this if you forget to call `app.serveFolder(__dirname)` or point to any other folder your web content is in.

You need to tell Carlo where your web files are.

**Comment by tsengkasing** [comment]
I got it. I made a stupid mistake. Sorry to bother you.

**Comment by gibatronic** [comment]
I got that error with the [`README.md`](https://github.com/GoogleChromeLabs/carlo/blob/0b07f603c0a3062cec9e804e340df16a88d5a12d/README.md#usage) example... `app.serveFolder` is being called.
`node 8.12.0` `carlo 0.9.7` `chrome 70.0.3538.77` `macOS 10.14.1`

**Comment by pavelfeldman** [comment]
Did you copy `example.html` beside your `example.js`?

**Comment by gibatronic** [comment]
My bad, I was pointing to the wrong place in `app.serveFolder`.
