### ISSUE TITLE
Cannot find module carlo

### ISSUE THREAD

**Issue by OumaWu** [GoogleChromeLabs/carlo#96]
### **After I run the example.js, it throws an error message:**

"D:\Projects\Web\Node\carlo>node example.js
internal/modules/cjs/loader.js:582
throw err; 

Error: Cannot find module 'carlo' 
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
at Function.Module._load (internal/modules/cjs/loader.js:506:25) 
at Module.require (internal/modules/cjs/loader.js:636:17) 
at require (internal/modules/cjs/helpers.js:20:18) 
at Object.<anonymous> (D:\Projects\Web\Node\carlo\example.js:1:77)
at Module._compile (internal/modules/cjs/loader.js:688:30) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) 
at Module. load (internal/modules/cjs/loader.js:598:32) 
at tryModuleLoad (internal/modules/cjs/loader.js:537:12) 
at Function.Module._load (internal/modules/cjs/loader.js:529:3) "

**Comment by vsemozhetbyt** [comment]
1. How and where did you install `carlo`?
2. Could you provide `example.js` code?

**Comment by OumaWu** [comment]
But I still can't run the code, because I didn't intall Google Chrome in C drive, is there a way to fix that ?
"D:\Projects\Web\Node\carlo>node example.js
Could not find Chrome installation, please make sure Chrome browser is installed from https://www.google.com/chrome/."

**Comment by geekplux** [comment]
please set your `executablePath` option when you `carlo.launch`.

**Comment by OumaWu** [comment]
Thx, I've launched the program successfully.
